packages:
  - ui

minimumReleaseAge: 20160
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
blockExoticSubdeps: true
strictDepBuilds: true
dangerouslyAllowAllBuilds: false
verifyDepsBeforeRun: error

allowBuilds:
  esbuild: true
