// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dal_obscura/flight/v1/read.proto
// Protobuf Java Version: 4.35.0

package io.dalobscura.flight.v1;

@com.google.protobuf.Generated
public final class DalObscuraFlightProto extends com.google.protobuf.GeneratedFile {
  private DalObscuraFlightProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "DalObscuraFlightProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlanRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dal_obscura.flight.v1.PlanRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 protocol_version = 1;</code>
     * @return The protocolVersion.
     */
    int getProtocolVersion();

    /**
     * <code>string catalog = 2;</code>
     * @return The catalog.
     */
    java.lang.String getCatalog();
    /**
     * <code>string catalog = 2;</code>
     * @return The bytes for catalog.
     */
    com.google.protobuf.ByteString
        getCatalogBytes();

    /**
     * <code>string target = 3;</code>
     * @return The target.
     */
    java.lang.String getTarget();
    /**
     * <code>string target = 3;</code>
     * @return The bytes for target.
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    /**
     * <code>repeated string columns = 4;</code>
     * @return A list containing the columns.
     */
    java.util.List<java.lang.String>
        getColumnsList();
    /**
     * <code>repeated string columns = 4;</code>
     * @return The count of columns.
     */
    int getColumnsCount();
    /**
     * <code>repeated string columns = 4;</code>
     * @param index The index of the element to return.
     * @return The columns at the given index.
     */
    java.lang.String getColumns(int index);
    /**
     * <code>repeated string columns = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the columns at the given index.
     */
    com.google.protobuf.ByteString
        getColumnsBytes(int index);

    /**
     * <code>string row_filter = 5;</code>
     * @return The rowFilter.
     */
    java.lang.String getRowFilter();
    /**
     * <code>string row_filter = 5;</code>
     * @return The bytes for rowFilter.
     */
    com.google.protobuf.ByteString
        getRowFilterBytes();
  }
  /**
   * Protobuf type {@code dal_obscura.flight.v1.PlanRequest}
   */
  public static final class PlanRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dal_obscura.flight.v1.PlanRequest)
      PlanRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 0,
        /* suffix= */ "",
        "PlanRequest");
    }
    // Use PlanRequest.newBuilder() to construct.
    private PlanRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlanRequest() {
      catalog_ = "";
      target_ = "";
      columns_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      rowFilter_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dalobscura.flight.v1.DalObscuraFlightProto.internal_static_dal_obscura_flight_v1_PlanRequest_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.dalobscura.flight.v1.DalObscuraFlightProto.internal_static_dal_obscura_flight_v1_PlanRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dalobscura.flight.v1.DalObscuraFlightProto.internal_static_dal_obscura_flight_v1_PlanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest.class, io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest.Builder.class);
    }

    public static final int PROTOCOL_VERSION_FIELD_NUMBER = 1;
    private int protocolVersion_ = 0;
    /**
     * <code>uint32 protocol_version = 1;</code>
     * @return The protocolVersion.
     */
    @java.lang.Override
    public int getProtocolVersion() {
      return protocolVersion_;
    }

    public static final int CATALOG_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object catalog_ = "";
    /**
     * <code>string catalog = 2;</code>
     * @return The catalog.
     */
    @java.lang.Override
    public java.lang.String getCatalog() {
      java.lang.Object ref = catalog_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        catalog_ = s;
        return s;
      }
    }
    /**
     * <code>string catalog = 2;</code>
     * @return The bytes for catalog.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCatalogBytes() {
      java.lang.Object ref = catalog_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        catalog_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGET_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object target_ = "";
    /**
     * <code>string target = 3;</code>
     * @return The target.
     */
    @java.lang.Override
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        target_ = s;
        return s;
      }
    }
    /**
     * <code>string target = 3;</code>
     * @return The bytes for target.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMNS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList columns_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string columns = 4;</code>
     * @return A list containing the columns.
     */
    public com.google.protobuf.ProtocolStringList
        getColumnsList() {
      return columns_;
    }
    /**
     * <code>repeated string columns = 4;</code>
     * @return The count of columns.
     */
    public int getColumnsCount() {
      return columns_.size();
    }
    /**
     * <code>repeated string columns = 4;</code>
     * @param index The index of the element to return.
     * @return The columns at the given index.
     */
    public java.lang.String getColumns(int index) {
      return columns_.get(index);
    }
    /**
     * <code>repeated string columns = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the columns at the given index.
     */
    public com.google.protobuf.ByteString
        getColumnsBytes(int index) {
      return columns_.getByteString(index);
    }

    public static final int ROW_FILTER_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rowFilter_ = "";
    /**
     * <code>string row_filter = 5;</code>
     * @return The rowFilter.
     */
    @java.lang.Override
    public java.lang.String getRowFilter() {
      java.lang.Object ref = rowFilter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rowFilter_ = s;
        return s;
      }
    }
    /**
     * <code>string row_filter = 5;</code>
     * @return The bytes for rowFilter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRowFilterBytes() {
      java.lang.Object ref = rowFilter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rowFilter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protocolVersion_ != 0) {
        output.writeUInt32(1, protocolVersion_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(catalog_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, catalog_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(target_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, target_);
      }
      for (int i = 0; i < columns_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, columns_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rowFilter_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, rowFilter_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (protocolVersion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, protocolVersion_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(catalog_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, catalog_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(target_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, target_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < columns_.size(); i++) {
          dataSize += computeStringSizeNoTag(columns_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getColumnsList().size();
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rowFilter_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, rowFilter_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest)) {
        return super.equals(obj);
      }
      io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest other = (io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest) obj;

      if (getProtocolVersion()
          != other.getProtocolVersion()) return false;
      if (!getCatalog()
          .equals(other.getCatalog())) return false;
      if (!getTarget()
          .equals(other.getTarget())) return false;
      if (!getColumnsList()
          .equals(other.getColumnsList())) return false;
      if (!getRowFilter()
          .equals(other.getRowFilter())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROTOCOL_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getProtocolVersion();
      hash = (37 * hash) + CATALOG_FIELD_NUMBER;
      hash = (53 * hash) + getCatalog().hashCode();
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTarget().hashCode();
      if (getColumnsCount() > 0) {
        hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
        hash = (53 * hash) + getColumnsList().hashCode();
      }
      hash = (37 * hash) + ROW_FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getRowFilter().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dal_obscura.flight.v1.PlanRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dal_obscura.flight.v1.PlanRequest)
        io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.dalobscura.flight.v1.DalObscuraFlightProto.internal_static_dal_obscura_flight_v1_PlanRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.dalobscura.flight.v1.DalObscuraFlightProto.internal_static_dal_obscura_flight_v1_PlanRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest.class, io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest.Builder.class);
      }

      // Construct using io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        protocolVersion_ = 0;
        catalog_ = "";
        target_ = "";
        columns_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        rowFilter_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.dalobscura.flight.v1.DalObscuraFlightProto.internal_static_dal_obscura_flight_v1_PlanRequest_descriptor;
      }

      @java.lang.Override
      public io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest getDefaultInstanceForType() {
        return io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest build() {
        io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest buildPartial() {
        io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest result = new io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.protocolVersion_ = protocolVersion_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.catalog_ = catalog_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.target_ = target_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          columns_.makeImmutable();
          result.columns_ = columns_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.rowFilter_ = rowFilter_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest) {
          return mergeFrom((io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest other) {
        if (other == io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest.getDefaultInstance()) return this;
        if (other.getProtocolVersion() != 0) {
          setProtocolVersion(other.getProtocolVersion());
        }
        if (!other.getCatalog().isEmpty()) {
          catalog_ = other.catalog_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getTarget().isEmpty()) {
          target_ = other.target_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.columns_.isEmpty()) {
          if (columns_.isEmpty()) {
            columns_ = other.columns_;
            bitField0_ |= 0x00000008;
          } else {
            ensureColumnsIsMutable();
            columns_.addAll(other.columns_);
          }
          onChanged();
        }
        if (!other.getRowFilter().isEmpty()) {
          rowFilter_ = other.rowFilter_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                protocolVersion_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                catalog_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                target_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                ensureColumnsIsMutable();
                columns_.add(input.readStringRequireUtf8());
                break;
              } // case 34
              case 42: {
                rowFilter_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int protocolVersion_ ;
      /**
       * <code>uint32 protocol_version = 1;</code>
       * @return The protocolVersion.
       */
      @java.lang.Override
      public int getProtocolVersion() {
        return protocolVersion_;
      }
      /**
       * <code>uint32 protocol_version = 1;</code>
       * @param value The protocolVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolVersion(int value) {

        protocolVersion_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 protocol_version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocolVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protocolVersion_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object catalog_ = "";
      /**
       * <code>string catalog = 2;</code>
       * @return The catalog.
       */
      public java.lang.String getCatalog() {
        java.lang.Object ref = catalog_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          catalog_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string catalog = 2;</code>
       * @return The bytes for catalog.
       */
      public com.google.protobuf.ByteString
          getCatalogBytes() {
        java.lang.Object ref = catalog_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          catalog_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string catalog = 2;</code>
       * @param value The catalog to set.
       * @return This builder for chaining.
       */
      public Builder setCatalog(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        catalog_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string catalog = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCatalog() {
        catalog_ = getDefaultInstance().getCatalog();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string catalog = 2;</code>
       * @param value The bytes for catalog to set.
       * @return This builder for chaining.
       */
      public Builder setCatalogBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        catalog_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object target_ = "";
      /**
       * <code>string target = 3;</code>
       * @return The target.
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          target_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string target = 3;</code>
       * @return The bytes for target.
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string target = 3;</code>
       * @param value The target to set.
       * @return This builder for chaining.
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        target_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string target = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTarget() {
        target_ = getDefaultInstance().getTarget();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string target = 3;</code>
       * @param value The bytes for target to set.
       * @return This builder for chaining.
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        target_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList columns_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureColumnsIsMutable() {
        if (!columns_.isModifiable()) {
          columns_ = new com.google.protobuf.LazyStringArrayList(columns_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string columns = 4;</code>
       * @return A list containing the columns.
       */
      public com.google.protobuf.ProtocolStringList
          getColumnsList() {
        columns_.makeImmutable();
        return columns_;
      }
      /**
       * <code>repeated string columns = 4;</code>
       * @return The count of columns.
       */
      public int getColumnsCount() {
        return columns_.size();
      }
      /**
       * <code>repeated string columns = 4;</code>
       * @param index The index of the element to return.
       * @return The columns at the given index.
       */
      public java.lang.String getColumns(int index) {
        return columns_.get(index);
      }
      /**
       * <code>repeated string columns = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the columns at the given index.
       */
      public com.google.protobuf.ByteString
          getColumnsBytes(int index) {
        return columns_.getByteString(index);
      }
      /**
       * <code>repeated string columns = 4;</code>
       * @param index The index to set the value at.
       * @param value The columns to set.
       * @return This builder for chaining.
       */
      public Builder setColumns(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureColumnsIsMutable();
        columns_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columns = 4;</code>
       * @param value The columns to add.
       * @return This builder for chaining.
       */
      public Builder addColumns(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureColumnsIsMutable();
        columns_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columns = 4;</code>
       * @param values The columns to add.
       * @return This builder for chaining.
       */
      public Builder addAllColumns(
          java.lang.Iterable<java.lang.String> values) {
        ensureColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, columns_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columns = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearColumns() {
        columns_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columns = 4;</code>
       * @param value The bytes of the columns to add.
       * @return This builder for chaining.
       */
      public Builder addColumnsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureColumnsIsMutable();
        columns_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object rowFilter_ = "";
      /**
       * <code>string row_filter = 5;</code>
       * @return The rowFilter.
       */
      public java.lang.String getRowFilter() {
        java.lang.Object ref = rowFilter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rowFilter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string row_filter = 5;</code>
       * @return The bytes for rowFilter.
       */
      public com.google.protobuf.ByteString
          getRowFilterBytes() {
        java.lang.Object ref = rowFilter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rowFilter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string row_filter = 5;</code>
       * @param value The rowFilter to set.
       * @return This builder for chaining.
       */
      public Builder setRowFilter(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        rowFilter_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string row_filter = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRowFilter() {
        rowFilter_ = getDefaultInstance().getRowFilter();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string row_filter = 5;</code>
       * @param value The bytes for rowFilter to set.
       * @return This builder for chaining.
       */
      public Builder setRowFilterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rowFilter_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dal_obscura.flight.v1.PlanRequest)
    }

    // @@protoc_insertion_point(class_scope:dal_obscura.flight.v1.PlanRequest)
    private static final io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest();
    }

    public static io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlanRequest>
        PARSER = new com.google.protobuf.AbstractParser<PlanRequest>() {
      @java.lang.Override
      public PlanRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlanRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlanRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.dalobscura.flight.v1.DalObscuraFlightProto.PlanRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dal_obscura_flight_v1_PlanRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dal_obscura_flight_v1_PlanRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n dal_obscura/flight/v1/read.proto\022\025dal_" +
      "obscura.flight.v1\"m\n\013PlanRequest\022\030\n\020prot" +
      "ocol_version\030\001 \001(\r\022\017\n\007catalog\030\002 \001(\t\022\016\n\006t" +
      "arget\030\003 \001(\t\022\017\n\007columns\030\004 \003(\t\022\022\n\nrow_filt" +
      "er\030\005 \001(\tB0\n\027io.dalobscura.flight.v1B\025Dal" +
      "ObscuraFlightProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dal_obscura_flight_v1_PlanRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_dal_obscura_flight_v1_PlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dal_obscura_flight_v1_PlanRequest_descriptor,
        new java.lang.String[] { "ProtocolVersion", "Catalog", "Target", "Columns", "RowFilter", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
