agent {
  data_dir = "/run/spire/agent/data"
  log_level = "INFO"
  server_address = "spire-server"
  server_port = "8081"
  socket_path = "/run/spire/agent/public/api.sock"
  trust_domain = "example.org"
  insecure_bootstrap = true
}

plugins {
  NodeAttestor "join_token" {
    plugin_data {}
  }

  KeyManager "disk" {
    plugin_data {
      directory = "/run/spire/agent/data"
    }
  }

  WorkloadAttestor "unix" {
    plugin_data {}
  }
}
