# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dal_obscura/flight/v1/read.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 0, "", "dal_obscura/flight/v1/read.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n dal_obscura/flight/v1/read.proto\x12\x15\x64\x61l_obscura.flight.v1"m\n\x0bPlanRequest\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x0f\n\x07\x63\x61talog\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0f\n\x07\x63olumns\x18\x04 \x03(\t\x12\x12\n\nrow_filter\x18\x05 \x01(\tB0\n\x17io.dalobscura.flight.v1B\x15\x44\x61lObscuraFlightProtob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "dal_obscura.flight.v1.read_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\027io.dalobscura.flight.v1B\025DalObscuraFlightProto"
    _globals["_PLANREQUEST"]._serialized_start = 59
    _globals["_PLANREQUEST"]._serialized_end = 168
# @@protoc_insertion_point(module_scope)
