from collections.abc import Mapping

import pyarrow as pa

class Reader:
    def __init__(
        self, location: str, snapshot: int, properties: Mapping[str, str], seconds: float
    ) -> None: ...
    def files(self) -> list[tuple[str, int]]: ...
    def start(self, fragments: list[tuple[str, int, int]]) -> Batches: ...

class Batches:
    def next(self, seconds: float) -> pa.RecordBatch | None: ...
    def close(self) -> None: ...
